### PR TITLE
Email Notifications in Lead/Deal Activity

### PR DESCRIPTION
**Pull request by neelbhanushali**
PR for #172 

Adding entries from `automated_messages` to `activities` in `crm.api.activities.get_activities` API

### CODE REVIEW

**Comment by neelbhanushali** [comment]
@shariquerik 

Automated messages showing in activity and email

Lead -> Activity
image

Lead -> Email
image

Deal -> Activity
image

Deal -> Email
image

**Comment by shariquerik** [comment]
@neelbhanushali it looks good but we should also show in UI that it came from notification

**Comment by shariquerik** [comment]
@neelbhanushali no need to write the same code again for automated_messages

This should do it
```
for communication in docinfo.communications + docinfo.automated_messages
```

**Pull request merged**
