### PR TITLE
feat: Create Quotation, Contact and Customer in ERPNext from Deal

### PR DESCRIPTION
**Pull request by nabinhait**
- Enable ERPNext Integration from ERPNext Settings and set API credentials
Screenshot 2024-09-12 at 7 22 56 PM

- Add CRM Form Script to show "Create Quotation" button in CRM Deal
- Open a new Quotation form
    - For remote ERPNext Site, create Prospect and make a quotation against the prospect
    - For same site, create Quotation against CRM Deal
- On Won deal, create customer and contact on erpnext site

Depends-on https://github.com/frappe/erpnext/pull/43198

### CODE REVIEW

**Comment by ajiragroup** [comment]
Getting this error during ERPnext setup.
image

**Comment by nabinhait** [comment]
@shariquerik Can you check this?

**Comment by shariquerik** [comment]
> Getting this error during ERPnext setup. image
> 
> Context: Erpnext on same site.

@ajiragroup can you share the version of Frappe CRM & ERPNext installed?

**Comment by ajiragroup** [comment]
image

**Comment by shariquerik** [comment]
> image @shariquerik

Is your site on frappecloud? Can I get access to check what is the issue.

**Comment by ajiragroup** [comment]
No not on Frappe Cloud. It is self hosted. I can give you access though.  How would you like to proceed ?

**Comment by falahteam** [comment]
Customer is not creating automatic when status change i explain the problem in detail in below post please check 

https://discuss.frappe.io/t/frappe-crm-issue-when-enable-the-customer-create-on-status-change-in-setting/133982

**Pull request merged**
