### PR TITLE
fix: splashscreen layout on pwa had oversized branding

### PR DESCRIPTION
**Pull request by esafwan**
This PR improves the splash screen by centering and scaling down the Frappe CRM logo, improving visual branding and loading experience on iPhone. Before and after screenshots are included for comparison.

**Screenshot of app loading before fix on iPhone 12:**

**Screenshot of app loading after fix on iPhone 12:**

### CODE REVIEW

**Comment by shariquerik** [comment]
Since we are doing this lets replace it with the latest logo

```
<svg width="300" height="300" viewBox="0 0 300 300" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M214.286 0H85.7143C38.3756 0 0 38.3756 0 85.7143V214.286C0 261.624 38.3756 300 85.7143 300H214.286C261.624 300 300 261.624 300 214.286V85.7143C300 38.3756 261.624 0 214.286 0Z" fill="#EF0BF5"/>
<path d="M64.2858 90.9642V112.393H214.286V140.571L160.179 193.178V208.929L139.714 208.821V193.178L85.7143 140.571H64.2858V149.571L118.286 202.179V230.035L181.607 230.571V202.179L235.714 149.571V90.9642H64.2858Z" fill="white"/>
</svg>
```

**Comment by esafwan** [comment]
Sure

**Comment by esafwan** [comment]
@shariquerik The logo on screens have been updated. Do have a look.

**Comment by shariquerik** [comment]
@esafwan splashscreen in android is still very big

**Comment by esafwan** [comment]
I will check this. I only tested on iPhone. Let me try to figure which file is being loaded on android. Could it be just loading the  logo on a white background? 

Meanwhile, have you been able to look at the splash screen files and logo sizes I have given? It is small on larger res. But in some sizes, it is relatively big.

**Pull request merged**
